/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AlertsAlertIdRouteImport } from "./routes/alerts.$alertId";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AlertsAlertIdRoute = AlertsAlertIdRouteImport.update({
  id: "/alerts/$alertId",
  path: "/alerts/$alertId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/alerts/$alertId": typeof AlertsAlertIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/alerts/$alertId": typeof AlertsAlertIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/alerts/$alertId": typeof AlertsAlertIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/alerts/$alertId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/alerts/$alertId";
  id: "__root__" | "/" | "/alerts/$alertId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AlertsAlertIdRoute: typeof AlertsAlertIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/alerts/$alertId": {
      id: "/alerts/$alertId";
      path: "/alerts/$alertId";
      fullPath: "/alerts/$alertId";
      preLoaderRoute: typeof AlertsAlertIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsAlertIdRoute: AlertsAlertIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
