// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CreateActionApiV1LookupActionsPostData,
  CreateActionApiV1LookupActionsPostErrors,
  CreateActionApiV1LookupActionsPostResponses,
  CreateMachineApiV1LookupMachinesPostData,
  CreateMachineApiV1LookupMachinesPostErrors,
  CreateMachineApiV1LookupMachinesPostResponses,
  CreateReasonApiV1LookupReasonsPostData,
  CreateReasonApiV1LookupReasonsPostErrors,
  CreateReasonApiV1LookupReasonsPostResponses,
  CreateSensorApiV1LookupSensorsPostData,
  CreateSensorApiV1LookupSensorsPostErrors,
  CreateSensorApiV1LookupSensorsPostResponses,
  GetActionsApiV1LookupActionsGetData,
  GetActionsApiV1LookupActionsGetErrors,
  GetActionsApiV1LookupActionsGetResponses,
  GetAlertApiV1AlertsAlertIdGetData,
  GetAlertApiV1AlertsAlertIdGetErrors,
  GetAlertApiV1AlertsAlertIdGetResponses,
  GetAudioApiV1AlertsAlertIdAudioGetData,
  GetAudioApiV1AlertsAlertIdAudioGetErrors,
  GetAudioApiV1AlertsAlertIdAudioGetResponses,
  GetBaselineAudioApiV1AlertsAlertIdBaselineAudioGetData,
  GetBaselineAudioApiV1AlertsAlertIdBaselineAudioGetErrors,
  GetBaselineAudioApiV1AlertsAlertIdBaselineAudioGetResponses,
  GetBaselineSpectrogramApiV1AlertsAlertIdBaselineSpectrogramGetData,
  GetBaselineSpectrogramApiV1AlertsAlertIdBaselineSpectrogramGetErrors,
  GetBaselineSpectrogramApiV1AlertsAlertIdBaselineSpectrogramGetResponses,
  GetBaselineWaveformApiV1AlertsAlertIdBaselineWaveformGetData,
  GetBaselineWaveformApiV1AlertsAlertIdBaselineWaveformGetErrors,
  GetBaselineWaveformApiV1AlertsAlertIdBaselineWaveformGetResponses,
  GetMachinesApiV1LookupMachinesGetData,
  GetMachinesApiV1LookupMachinesGetErrors,
  GetMachinesApiV1LookupMachinesGetResponses,
  GetReasonsApiV1LookupReasonsGetData,
  GetReasonsApiV1LookupReasonsGetErrors,
  GetReasonsApiV1LookupReasonsGetResponses,
  GetSensorsApiV1LookupSensorsGetData,
  GetSensorsApiV1LookupSensorsGetErrors,
  GetSensorsApiV1LookupSensorsGetResponses,
  GetSpectrogramApiV1AlertsAlertIdSpectrogramGetData,
  GetSpectrogramApiV1AlertsAlertIdSpectrogramGetErrors,
  GetSpectrogramApiV1AlertsAlertIdSpectrogramGetResponses,
  GetWaveformApiV1AlertsAlertIdWaveformGetData,
  GetWaveformApiV1AlertsAlertIdWaveformGetErrors,
  GetWaveformApiV1AlertsAlertIdWaveformGetResponses,
  HealthApiV1HealthGetData,
  HealthApiV1HealthGetResponses,
  HealthCompatHealthGetData,
  HealthCompatHealthGetResponses,
  ListAlertsApiV1AlertsGetData,
  ListAlertsApiV1AlertsGetErrors,
  ListAlertsApiV1AlertsGetResponses,
  UpdateActionApiV1LookupActionsActionIdPatchData,
  UpdateActionApiV1LookupActionsActionIdPatchErrors,
  UpdateActionApiV1LookupActionsActionIdPatchResponses,
  UpdateAlertApiV1AlertsAlertIdPatchData,
  UpdateAlertApiV1AlertsAlertIdPatchErrors,
  UpdateAlertApiV1AlertsAlertIdPatchResponses,
  UpdateMachineApiV1LookupMachinesMachineIdPatchData,
  UpdateMachineApiV1LookupMachinesMachineIdPatchErrors,
  UpdateMachineApiV1LookupMachinesMachineIdPatchResponses,
  UpdateReasonApiV1LookupReasonsReasonIdPatchData,
  UpdateReasonApiV1LookupReasonsReasonIdPatchErrors,
  UpdateReasonApiV1LookupReasonsReasonIdPatchResponses,
  UpdateSensorApiV1LookupSensorsSensorIdPatchData,
  UpdateSensorApiV1LookupSensorsSensorIdPatchErrors,
  UpdateSensorApiV1LookupSensorsSensorIdPatchResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List Alerts
 */
export const listAlertsApiV1AlertsGet = <ThrowOnError extends boolean = false>(
  options?: Options<ListAlertsApiV1AlertsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    ListAlertsApiV1AlertsGetResponses,
    ListAlertsApiV1AlertsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/alerts", ...options });

/**
 * Get Alert
 */
export const getAlertApiV1AlertsAlertIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetAlertApiV1AlertsAlertIdGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAlertApiV1AlertsAlertIdGetResponses,
    GetAlertApiV1AlertsAlertIdGetErrors,
    ThrowOnError
  >({ url: "/api/v1/alerts/{alert_id}", ...options });

/**
 * Update Alert
 */
export const updateAlertApiV1AlertsAlertIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAlertApiV1AlertsAlertIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateAlertApiV1AlertsAlertIdPatchResponses,
    UpdateAlertApiV1AlertsAlertIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/alerts/{alert_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Audio
 */
export const getAudioApiV1AlertsAlertIdAudioGet = <ThrowOnError extends boolean = false>(
  options: Options<GetAudioApiV1AlertsAlertIdAudioGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetAudioApiV1AlertsAlertIdAudioGetResponses,
    GetAudioApiV1AlertsAlertIdAudioGetErrors,
    ThrowOnError
  >({ url: "/api/v1/alerts/{alert_id}/audio", ...options });

/**
 * Get Waveform
 */
export const getWaveformApiV1AlertsAlertIdWaveformGet = <ThrowOnError extends boolean = false>(
  options: Options<GetWaveformApiV1AlertsAlertIdWaveformGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetWaveformApiV1AlertsAlertIdWaveformGetResponses,
    GetWaveformApiV1AlertsAlertIdWaveformGetErrors,
    ThrowOnError
  >({ url: "/api/v1/alerts/{alert_id}/waveform", ...options });

/**
 * Get Spectrogram
 */
export const getSpectrogramApiV1AlertsAlertIdSpectrogramGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetSpectrogramApiV1AlertsAlertIdSpectrogramGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSpectrogramApiV1AlertsAlertIdSpectrogramGetResponses,
    GetSpectrogramApiV1AlertsAlertIdSpectrogramGetErrors,
    ThrowOnError
  >({ url: "/api/v1/alerts/{alert_id}/spectrogram", ...options });

/**
 * Get Baseline Audio
 */
export const getBaselineAudioApiV1AlertsAlertIdBaselineAudioGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetBaselineAudioApiV1AlertsAlertIdBaselineAudioGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetBaselineAudioApiV1AlertsAlertIdBaselineAudioGetResponses,
    GetBaselineAudioApiV1AlertsAlertIdBaselineAudioGetErrors,
    ThrowOnError
  >({ url: "/api/v1/alerts/{alert_id}/baseline/audio", ...options });

/**
 * Get Baseline Waveform
 */
export const getBaselineWaveformApiV1AlertsAlertIdBaselineWaveformGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetBaselineWaveformApiV1AlertsAlertIdBaselineWaveformGetData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetBaselineWaveformApiV1AlertsAlertIdBaselineWaveformGetResponses,
    GetBaselineWaveformApiV1AlertsAlertIdBaselineWaveformGetErrors,
    ThrowOnError
  >({ url: "/api/v1/alerts/{alert_id}/baseline/waveform", ...options });

/**
 * Get Baseline Spectrogram
 */
export const getBaselineSpectrogramApiV1AlertsAlertIdBaselineSpectrogramGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetBaselineSpectrogramApiV1AlertsAlertIdBaselineSpectrogramGetData,
    ThrowOnError
  >,
) =>
  (options.client ?? client).get<
    GetBaselineSpectrogramApiV1AlertsAlertIdBaselineSpectrogramGetResponses,
    GetBaselineSpectrogramApiV1AlertsAlertIdBaselineSpectrogramGetErrors,
    ThrowOnError
  >({ url: "/api/v1/alerts/{alert_id}/baseline/spectrogram", ...options });

/**
 * Get Machines
 */
export const getMachinesApiV1LookupMachinesGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMachinesApiV1LookupMachinesGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetMachinesApiV1LookupMachinesGetResponses,
    GetMachinesApiV1LookupMachinesGetErrors,
    ThrowOnError
  >({ url: "/api/v1/lookup/machines", ...options });

/**
 * Create Machine
 */
export const createMachineApiV1LookupMachinesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateMachineApiV1LookupMachinesPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateMachineApiV1LookupMachinesPostResponses,
    CreateMachineApiV1LookupMachinesPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/lookup/machines",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Machine
 */
export const updateMachineApiV1LookupMachinesMachineIdPatch = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateMachineApiV1LookupMachinesMachineIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateMachineApiV1LookupMachinesMachineIdPatchResponses,
    UpdateMachineApiV1LookupMachinesMachineIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/lookup/machines/{machine_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Reasons
 */
export const getReasonsApiV1LookupReasonsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetReasonsApiV1LookupReasonsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetReasonsApiV1LookupReasonsGetResponses,
    GetReasonsApiV1LookupReasonsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/lookup/reasons", ...options });

/**
 * Create Reason
 */
export const createReasonApiV1LookupReasonsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateReasonApiV1LookupReasonsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateReasonApiV1LookupReasonsPostResponses,
    CreateReasonApiV1LookupReasonsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/lookup/reasons",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Reason
 */
export const updateReasonApiV1LookupReasonsReasonIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<UpdateReasonApiV1LookupReasonsReasonIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateReasonApiV1LookupReasonsReasonIdPatchResponses,
    UpdateReasonApiV1LookupReasonsReasonIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/lookup/reasons/{reason_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Actions
 */
export const getActionsApiV1LookupActionsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetActionsApiV1LookupActionsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetActionsApiV1LookupActionsGetResponses,
    GetActionsApiV1LookupActionsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/lookup/actions", ...options });

/**
 * Create Action
 */
export const createActionApiV1LookupActionsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateActionApiV1LookupActionsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateActionApiV1LookupActionsPostResponses,
    CreateActionApiV1LookupActionsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/lookup/actions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Action
 */
export const updateActionApiV1LookupActionsActionIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<UpdateActionApiV1LookupActionsActionIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateActionApiV1LookupActionsActionIdPatchResponses,
    UpdateActionApiV1LookupActionsActionIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/lookup/actions/{action_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Sensors
 */
export const getSensorsApiV1LookupSensorsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetSensorsApiV1LookupSensorsGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSensorsApiV1LookupSensorsGetResponses,
    GetSensorsApiV1LookupSensorsGetErrors,
    ThrowOnError
  >({ url: "/api/v1/lookup/sensors", ...options });

/**
 * Create Sensor
 */
export const createSensorApiV1LookupSensorsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateSensorApiV1LookupSensorsPostData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSensorApiV1LookupSensorsPostResponses,
    CreateSensorApiV1LookupSensorsPostErrors,
    ThrowOnError
  >({
    url: "/api/v1/lookup/sensors",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Update Sensor
 */
export const updateSensorApiV1LookupSensorsSensorIdPatch = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSensorApiV1LookupSensorsSensorIdPatchData, ThrowOnError>,
) =>
  (options.client ?? client).patch<
    UpdateSensorApiV1LookupSensorsSensorIdPatchResponses,
    UpdateSensorApiV1LookupSensorsSensorIdPatchErrors,
    ThrowOnError
  >({
    url: "/api/v1/lookup/sensors/{sensor_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Health
 *
 * Health check endpoint.
 */
export const healthApiV1HealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthApiV1HealthGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<HealthApiV1HealthGetResponses, unknown, ThrowOnError>({
    url: "/api/v1/health",
    ...options,
  });

/**
 * Health Compat
 *
 * Compatibility endpoint for existing callers.
 */
export const healthCompatHealthGet = <ThrowOnError extends boolean = false>(
  options?: Options<HealthCompatHealthGetData, ThrowOnError>,
) =>
  (options?.client ?? client).get<HealthCompatHealthGetResponses, unknown, ThrowOnError>({
    url: "/health",
    ...options,
  });
