// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { HealthApiV1HealthGetData, HealthApiV1HealthGetResponses, HealthCompatHealthGetData, HealthCompatHealthGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health
 *
 * Health check endpoint.
 */
export const healthApiV1HealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthApiV1HealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthApiV1HealthGetResponses, unknown, ThrowOnError>({ url: '/api/v1/health', ...options });

/**
 * Health Compat
 *
 * Compatibility endpoint for existing callers.
 */
export const healthCompatHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCompatHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthCompatHealthGetResponses, unknown, ThrowOnError>({ url: '/health', ...options });
