// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AlertResponse
 */
export type AlertResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Timestamp
   */
  timestamp: string;
  /**
   * Machine
   */
  machine: string;
  /**
   * Anomaly Type
   */
  anomaly_type: string;
  /**
   * Sensor
   */
  sensor: string;
  /**
   * Sound Clip
   */
  sound_clip: string;
  /**
   * Suspected Reason
   */
  suspected_reason: string | null;
  /**
   * Action
   */
  action: string | null;
  /**
   * Comment
   */
  comment: string | null;
};

/**
 * AlertUpdateRequest
 */
export type AlertUpdateRequest = {
  /**
   * Suspected Reason
   */
  suspected_reason?: string | null;
  /**
   * Action
   */
  action?: string | null;
  /**
   * Comment
   */
  comment?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LookupItem
 */
export type LookupItem = {
  /**
   * Id
   */
  id: string;
  /**
   * Name
   */
  name: string;
  /**
   * Category
   */
  category: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * WaveformResponse
 */
export type WaveformResponse = {
  /**
   * Alert Id
   */
  alert_id: number;
  /**
   * Sample Rate
   */
  sample_rate: number;
  /**
   * Duration Seconds
   */
  duration_seconds: number;
  /**
   * Times
   */
  times: Array<number>;
  /**
   * Amplitudes
   */
  amplitudes: Array<number>;
};

export type ListAlertsApiV1AlertsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Machine
     */
    machine?: string | null;
    /**
     * Anomaly
     */
    anomaly?: string | null;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
  };
  url: "/api/v1/alerts";
};

export type ListAlertsApiV1AlertsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListAlertsApiV1AlertsGetError =
  ListAlertsApiV1AlertsGetErrors[keyof ListAlertsApiV1AlertsGetErrors];

export type ListAlertsApiV1AlertsGetResponses = {
  /**
   * Response List Alerts Api V1 Alerts Get
   *
   * Successful Response
   */
  200: Array<AlertResponse>;
};

export type ListAlertsApiV1AlertsGetResponse =
  ListAlertsApiV1AlertsGetResponses[keyof ListAlertsApiV1AlertsGetResponses];

export type GetAlertApiV1AlertsAlertIdGetData = {
  body?: never;
  path: {
    /**
     * Alert Id
     */
    alert_id: number;
  };
  query?: never;
  url: "/api/v1/alerts/{alert_id}";
};

export type GetAlertApiV1AlertsAlertIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAlertApiV1AlertsAlertIdGetError =
  GetAlertApiV1AlertsAlertIdGetErrors[keyof GetAlertApiV1AlertsAlertIdGetErrors];

export type GetAlertApiV1AlertsAlertIdGetResponses = {
  /**
   * Successful Response
   */
  200: AlertResponse;
};

export type GetAlertApiV1AlertsAlertIdGetResponse =
  GetAlertApiV1AlertsAlertIdGetResponses[keyof GetAlertApiV1AlertsAlertIdGetResponses];

export type UpdateAlertApiV1AlertsAlertIdPatchData = {
  body: AlertUpdateRequest;
  path: {
    /**
     * Alert Id
     */
    alert_id: number;
  };
  query?: never;
  url: "/api/v1/alerts/{alert_id}";
};

export type UpdateAlertApiV1AlertsAlertIdPatchErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateAlertApiV1AlertsAlertIdPatchError =
  UpdateAlertApiV1AlertsAlertIdPatchErrors[keyof UpdateAlertApiV1AlertsAlertIdPatchErrors];

export type UpdateAlertApiV1AlertsAlertIdPatchResponses = {
  /**
   * Successful Response
   */
  200: AlertResponse;
};

export type UpdateAlertApiV1AlertsAlertIdPatchResponse =
  UpdateAlertApiV1AlertsAlertIdPatchResponses[keyof UpdateAlertApiV1AlertsAlertIdPatchResponses];

export type GetAudioApiV1AlertsAlertIdAudioGetData = {
  body?: never;
  path: {
    /**
     * Alert Id
     */
    alert_id: number;
  };
  query?: never;
  url: "/api/v1/alerts/{alert_id}/audio";
};

export type GetAudioApiV1AlertsAlertIdAudioGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetAudioApiV1AlertsAlertIdAudioGetError =
  GetAudioApiV1AlertsAlertIdAudioGetErrors[keyof GetAudioApiV1AlertsAlertIdAudioGetErrors];

export type GetAudioApiV1AlertsAlertIdAudioGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetWaveformApiV1AlertsAlertIdWaveformGetData = {
  body?: never;
  path: {
    /**
     * Alert Id
     */
    alert_id: number;
  };
  query?: never;
  url: "/api/v1/alerts/{alert_id}/waveform";
};

export type GetWaveformApiV1AlertsAlertIdWaveformGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetWaveformApiV1AlertsAlertIdWaveformGetError =
  GetWaveformApiV1AlertsAlertIdWaveformGetErrors[keyof GetWaveformApiV1AlertsAlertIdWaveformGetErrors];

export type GetWaveformApiV1AlertsAlertIdWaveformGetResponses = {
  /**
   * Successful Response
   */
  200: WaveformResponse;
};

export type GetWaveformApiV1AlertsAlertIdWaveformGetResponse =
  GetWaveformApiV1AlertsAlertIdWaveformGetResponses[keyof GetWaveformApiV1AlertsAlertIdWaveformGetResponses];

export type GetSpectrogramApiV1AlertsAlertIdSpectrogramGetData = {
  body?: never;
  path: {
    /**
     * Alert Id
     */
    alert_id: number;
  };
  query?: never;
  url: "/api/v1/alerts/{alert_id}/spectrogram";
};

export type GetSpectrogramApiV1AlertsAlertIdSpectrogramGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSpectrogramApiV1AlertsAlertIdSpectrogramGetError =
  GetSpectrogramApiV1AlertsAlertIdSpectrogramGetErrors[keyof GetSpectrogramApiV1AlertsAlertIdSpectrogramGetErrors];

export type GetSpectrogramApiV1AlertsAlertIdSpectrogramGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetLookupItemsApiV1LookupGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Category
     */
    category?: string | null;
    /**
     * Machine
     */
    machine?: string | null;
  };
  url: "/api/v1/lookup";
};

export type GetLookupItemsApiV1LookupGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLookupItemsApiV1LookupGetError =
  GetLookupItemsApiV1LookupGetErrors[keyof GetLookupItemsApiV1LookupGetErrors];

export type GetLookupItemsApiV1LookupGetResponses = {
  /**
   * Response Get Lookup Items Api V1 Lookup Get
   *
   * Successful Response
   */
  200: Array<LookupItem>;
};

export type GetLookupItemsApiV1LookupGetResponse =
  GetLookupItemsApiV1LookupGetResponses[keyof GetLookupItemsApiV1LookupGetResponses];

export type GetReasonsApiV1LookupReasonsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Machine
     */
    machine?: string | null;
  };
  url: "/api/v1/lookup/reasons";
};

export type GetReasonsApiV1LookupReasonsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetReasonsApiV1LookupReasonsGetError =
  GetReasonsApiV1LookupReasonsGetErrors[keyof GetReasonsApiV1LookupReasonsGetErrors];

export type GetReasonsApiV1LookupReasonsGetResponses = {
  /**
   * Response Get Reasons Api V1 Lookup Reasons Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type GetReasonsApiV1LookupReasonsGetResponse =
  GetReasonsApiV1LookupReasonsGetResponses[keyof GetReasonsApiV1LookupReasonsGetResponses];

export type GetActionsApiV1LookupActionsGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/lookup/actions";
};

export type GetActionsApiV1LookupActionsGetResponses = {
  /**
   * Response Get Actions Api V1 Lookup Actions Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type GetActionsApiV1LookupActionsGetResponse =
  GetActionsApiV1LookupActionsGetResponses[keyof GetActionsApiV1LookupActionsGetResponses];

export type HealthApiV1HealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/health";
};

export type HealthApiV1HealthGetResponses = {
  /**
   * Response Health Api V1 Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthApiV1HealthGetResponse =
  HealthApiV1HealthGetResponses[keyof HealthApiV1HealthGetResponses];

export type HealthCompatHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCompatHealthGetResponses = {
  /**
   * Response Health Compat Health Get
   *
   * Successful Response
   */
  200: {
    [key: string]: string;
  };
};

export type HealthCompatHealthGetResponse =
  HealthCompatHealthGetResponses[keyof HealthCompatHealthGetResponses];
