// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from "@tanstack/react-query";

import { client } from "../client.gen";
import {
  createActionApiV1LookupActionsPost,
  createMachineApiV1LookupMachinesPost,
  createReasonApiV1LookupReasonsPost,
  getActionsApiV1LookupActionsGet,
  getAlertApiV1AlertsAlertIdGet,
  getAudioApiV1AlertsAlertIdAudioGet,
  getMachinesApiV1LookupMachinesGet,
  getReasonsApiV1LookupReasonsGet,
  getSpectrogramApiV1AlertsAlertIdSpectrogramGet,
  getWaveformApiV1AlertsAlertIdWaveformGet,
  healthApiV1HealthGet,
  healthCompatHealthGet,
  listAlertsApiV1AlertsGet,
  type Options,
  updateActionApiV1LookupActionsActionIdPatch,
  updateAlertApiV1AlertsAlertIdPatch,
  updateMachineApiV1LookupMachinesMachineIdPatch,
  updateReasonApiV1LookupReasonsReasonIdPatch,
} from "../sdk.gen";
import type {
  CreateActionApiV1LookupActionsPostData,
  CreateActionApiV1LookupActionsPostError,
  CreateActionApiV1LookupActionsPostResponse,
  CreateMachineApiV1LookupMachinesPostData,
  CreateMachineApiV1LookupMachinesPostError,
  CreateMachineApiV1LookupMachinesPostResponse,
  CreateReasonApiV1LookupReasonsPostData,
  CreateReasonApiV1LookupReasonsPostError,
  CreateReasonApiV1LookupReasonsPostResponse,
  GetActionsApiV1LookupActionsGetData,
  GetActionsApiV1LookupActionsGetError,
  GetActionsApiV1LookupActionsGetResponse,
  GetAlertApiV1AlertsAlertIdGetData,
  GetAlertApiV1AlertsAlertIdGetError,
  GetAlertApiV1AlertsAlertIdGetResponse,
  GetAudioApiV1AlertsAlertIdAudioGetData,
  GetAudioApiV1AlertsAlertIdAudioGetError,
  GetMachinesApiV1LookupMachinesGetData,
  GetMachinesApiV1LookupMachinesGetError,
  GetMachinesApiV1LookupMachinesGetResponse,
  GetReasonsApiV1LookupReasonsGetData,
  GetReasonsApiV1LookupReasonsGetError,
  GetReasonsApiV1LookupReasonsGetResponse,
  GetSpectrogramApiV1AlertsAlertIdSpectrogramGetData,
  GetSpectrogramApiV1AlertsAlertIdSpectrogramGetError,
  GetWaveformApiV1AlertsAlertIdWaveformGetData,
  GetWaveformApiV1AlertsAlertIdWaveformGetError,
  GetWaveformApiV1AlertsAlertIdWaveformGetResponse,
  HealthApiV1HealthGetData,
  HealthApiV1HealthGetResponse,
  HealthCompatHealthGetData,
  HealthCompatHealthGetResponse,
  ListAlertsApiV1AlertsGetData,
  ListAlertsApiV1AlertsGetError,
  ListAlertsApiV1AlertsGetResponse,
  UpdateActionApiV1LookupActionsActionIdPatchData,
  UpdateActionApiV1LookupActionsActionIdPatchError,
  UpdateActionApiV1LookupActionsActionIdPatchResponse,
  UpdateAlertApiV1AlertsAlertIdPatchData,
  UpdateAlertApiV1AlertsAlertIdPatchError,
  UpdateAlertApiV1AlertsAlertIdPatchResponse,
  UpdateMachineApiV1LookupMachinesMachineIdPatchData,
  UpdateMachineApiV1LookupMachinesMachineIdPatchError,
  UpdateMachineApiV1LookupMachinesMachineIdPatchResponse,
  UpdateReasonApiV1LookupReasonsReasonIdPatchData,
  UpdateReasonApiV1LookupReasonsReasonIdPatchError,
  UpdateReasonApiV1LookupReasonsReasonIdPatchResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const listAlertsApiV1AlertsGetQueryKey = (options?: Options<ListAlertsApiV1AlertsGetData>) =>
  createQueryKey("listAlertsApiV1AlertsGet", options);

/**
 * List Alerts
 */
export const listAlertsApiV1AlertsGetOptions = (options?: Options<ListAlertsApiV1AlertsGetData>) =>
  queryOptions<
    ListAlertsApiV1AlertsGetResponse,
    ListAlertsApiV1AlertsGetError,
    ListAlertsApiV1AlertsGetResponse,
    ReturnType<typeof listAlertsApiV1AlertsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAlertsApiV1AlertsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAlertsApiV1AlertsGetQueryKey(options),
  });

export const getAlertApiV1AlertsAlertIdGetQueryKey = (
  options: Options<GetAlertApiV1AlertsAlertIdGetData>,
) => createQueryKey("getAlertApiV1AlertsAlertIdGet", options);

/**
 * Get Alert
 */
export const getAlertApiV1AlertsAlertIdGetOptions = (
  options: Options<GetAlertApiV1AlertsAlertIdGetData>,
) =>
  queryOptions<
    GetAlertApiV1AlertsAlertIdGetResponse,
    GetAlertApiV1AlertsAlertIdGetError,
    GetAlertApiV1AlertsAlertIdGetResponse,
    ReturnType<typeof getAlertApiV1AlertsAlertIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAlertApiV1AlertsAlertIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAlertApiV1AlertsAlertIdGetQueryKey(options),
  });

/**
 * Update Alert
 */
export const updateAlertApiV1AlertsAlertIdPatchMutation = (
  options?: Partial<Options<UpdateAlertApiV1AlertsAlertIdPatchData>>,
): UseMutationOptions<
  UpdateAlertApiV1AlertsAlertIdPatchResponse,
  UpdateAlertApiV1AlertsAlertIdPatchError,
  Options<UpdateAlertApiV1AlertsAlertIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateAlertApiV1AlertsAlertIdPatchResponse,
    UpdateAlertApiV1AlertsAlertIdPatchError,
    Options<UpdateAlertApiV1AlertsAlertIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateAlertApiV1AlertsAlertIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAudioApiV1AlertsAlertIdAudioGetQueryKey = (
  options: Options<GetAudioApiV1AlertsAlertIdAudioGetData>,
) => createQueryKey("getAudioApiV1AlertsAlertIdAudioGet", options);

/**
 * Get Audio
 */
export const getAudioApiV1AlertsAlertIdAudioGetOptions = (
  options: Options<GetAudioApiV1AlertsAlertIdAudioGetData>,
) =>
  queryOptions<
    unknown,
    GetAudioApiV1AlertsAlertIdAudioGetError,
    unknown,
    ReturnType<typeof getAudioApiV1AlertsAlertIdAudioGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAudioApiV1AlertsAlertIdAudioGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAudioApiV1AlertsAlertIdAudioGetQueryKey(options),
  });

export const getWaveformApiV1AlertsAlertIdWaveformGetQueryKey = (
  options: Options<GetWaveformApiV1AlertsAlertIdWaveformGetData>,
) => createQueryKey("getWaveformApiV1AlertsAlertIdWaveformGet", options);

/**
 * Get Waveform
 */
export const getWaveformApiV1AlertsAlertIdWaveformGetOptions = (
  options: Options<GetWaveformApiV1AlertsAlertIdWaveformGetData>,
) =>
  queryOptions<
    GetWaveformApiV1AlertsAlertIdWaveformGetResponse,
    GetWaveformApiV1AlertsAlertIdWaveformGetError,
    GetWaveformApiV1AlertsAlertIdWaveformGetResponse,
    ReturnType<typeof getWaveformApiV1AlertsAlertIdWaveformGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getWaveformApiV1AlertsAlertIdWaveformGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getWaveformApiV1AlertsAlertIdWaveformGetQueryKey(options),
  });

export const getSpectrogramApiV1AlertsAlertIdSpectrogramGetQueryKey = (
  options: Options<GetSpectrogramApiV1AlertsAlertIdSpectrogramGetData>,
) => createQueryKey("getSpectrogramApiV1AlertsAlertIdSpectrogramGet", options);

/**
 * Get Spectrogram
 */
export const getSpectrogramApiV1AlertsAlertIdSpectrogramGetOptions = (
  options: Options<GetSpectrogramApiV1AlertsAlertIdSpectrogramGetData>,
) =>
  queryOptions<
    unknown,
    GetSpectrogramApiV1AlertsAlertIdSpectrogramGetError,
    unknown,
    ReturnType<typeof getSpectrogramApiV1AlertsAlertIdSpectrogramGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSpectrogramApiV1AlertsAlertIdSpectrogramGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSpectrogramApiV1AlertsAlertIdSpectrogramGetQueryKey(options),
  });

export const getMachinesApiV1LookupMachinesGetQueryKey = (
  options?: Options<GetMachinesApiV1LookupMachinesGetData>,
) => createQueryKey("getMachinesApiV1LookupMachinesGet", options);

/**
 * Get Machines
 */
export const getMachinesApiV1LookupMachinesGetOptions = (
  options?: Options<GetMachinesApiV1LookupMachinesGetData>,
) =>
  queryOptions<
    GetMachinesApiV1LookupMachinesGetResponse,
    GetMachinesApiV1LookupMachinesGetError,
    GetMachinesApiV1LookupMachinesGetResponse,
    ReturnType<typeof getMachinesApiV1LookupMachinesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMachinesApiV1LookupMachinesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getMachinesApiV1LookupMachinesGetQueryKey(options),
  });

/**
 * Create Machine
 */
export const createMachineApiV1LookupMachinesPostMutation = (
  options?: Partial<Options<CreateMachineApiV1LookupMachinesPostData>>,
): UseMutationOptions<
  CreateMachineApiV1LookupMachinesPostResponse,
  CreateMachineApiV1LookupMachinesPostError,
  Options<CreateMachineApiV1LookupMachinesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateMachineApiV1LookupMachinesPostResponse,
    CreateMachineApiV1LookupMachinesPostError,
    Options<CreateMachineApiV1LookupMachinesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createMachineApiV1LookupMachinesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Machine
 */
export const updateMachineApiV1LookupMachinesMachineIdPatchMutation = (
  options?: Partial<Options<UpdateMachineApiV1LookupMachinesMachineIdPatchData>>,
): UseMutationOptions<
  UpdateMachineApiV1LookupMachinesMachineIdPatchResponse,
  UpdateMachineApiV1LookupMachinesMachineIdPatchError,
  Options<UpdateMachineApiV1LookupMachinesMachineIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateMachineApiV1LookupMachinesMachineIdPatchResponse,
    UpdateMachineApiV1LookupMachinesMachineIdPatchError,
    Options<UpdateMachineApiV1LookupMachinesMachineIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateMachineApiV1LookupMachinesMachineIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getReasonsApiV1LookupReasonsGetQueryKey = (
  options?: Options<GetReasonsApiV1LookupReasonsGetData>,
) => createQueryKey("getReasonsApiV1LookupReasonsGet", options);

/**
 * Get Reasons
 */
export const getReasonsApiV1LookupReasonsGetOptions = (
  options?: Options<GetReasonsApiV1LookupReasonsGetData>,
) =>
  queryOptions<
    GetReasonsApiV1LookupReasonsGetResponse,
    GetReasonsApiV1LookupReasonsGetError,
    GetReasonsApiV1LookupReasonsGetResponse,
    ReturnType<typeof getReasonsApiV1LookupReasonsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getReasonsApiV1LookupReasonsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getReasonsApiV1LookupReasonsGetQueryKey(options),
  });

/**
 * Create Reason
 */
export const createReasonApiV1LookupReasonsPostMutation = (
  options?: Partial<Options<CreateReasonApiV1LookupReasonsPostData>>,
): UseMutationOptions<
  CreateReasonApiV1LookupReasonsPostResponse,
  CreateReasonApiV1LookupReasonsPostError,
  Options<CreateReasonApiV1LookupReasonsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateReasonApiV1LookupReasonsPostResponse,
    CreateReasonApiV1LookupReasonsPostError,
    Options<CreateReasonApiV1LookupReasonsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createReasonApiV1LookupReasonsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Reason
 */
export const updateReasonApiV1LookupReasonsReasonIdPatchMutation = (
  options?: Partial<Options<UpdateReasonApiV1LookupReasonsReasonIdPatchData>>,
): UseMutationOptions<
  UpdateReasonApiV1LookupReasonsReasonIdPatchResponse,
  UpdateReasonApiV1LookupReasonsReasonIdPatchError,
  Options<UpdateReasonApiV1LookupReasonsReasonIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateReasonApiV1LookupReasonsReasonIdPatchResponse,
    UpdateReasonApiV1LookupReasonsReasonIdPatchError,
    Options<UpdateReasonApiV1LookupReasonsReasonIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateReasonApiV1LookupReasonsReasonIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getActionsApiV1LookupActionsGetQueryKey = (
  options?: Options<GetActionsApiV1LookupActionsGetData>,
) => createQueryKey("getActionsApiV1LookupActionsGet", options);

/**
 * Get Actions
 */
export const getActionsApiV1LookupActionsGetOptions = (
  options?: Options<GetActionsApiV1LookupActionsGetData>,
) =>
  queryOptions<
    GetActionsApiV1LookupActionsGetResponse,
    GetActionsApiV1LookupActionsGetError,
    GetActionsApiV1LookupActionsGetResponse,
    ReturnType<typeof getActionsApiV1LookupActionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getActionsApiV1LookupActionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getActionsApiV1LookupActionsGetQueryKey(options),
  });

/**
 * Create Action
 */
export const createActionApiV1LookupActionsPostMutation = (
  options?: Partial<Options<CreateActionApiV1LookupActionsPostData>>,
): UseMutationOptions<
  CreateActionApiV1LookupActionsPostResponse,
  CreateActionApiV1LookupActionsPostError,
  Options<CreateActionApiV1LookupActionsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateActionApiV1LookupActionsPostResponse,
    CreateActionApiV1LookupActionsPostError,
    Options<CreateActionApiV1LookupActionsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createActionApiV1LookupActionsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Update Action
 */
export const updateActionApiV1LookupActionsActionIdPatchMutation = (
  options?: Partial<Options<UpdateActionApiV1LookupActionsActionIdPatchData>>,
): UseMutationOptions<
  UpdateActionApiV1LookupActionsActionIdPatchResponse,
  UpdateActionApiV1LookupActionsActionIdPatchError,
  Options<UpdateActionApiV1LookupActionsActionIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateActionApiV1LookupActionsActionIdPatchResponse,
    UpdateActionApiV1LookupActionsActionIdPatchError,
    Options<UpdateActionApiV1LookupActionsActionIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateActionApiV1LookupActionsActionIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const healthApiV1HealthGetQueryKey = (options?: Options<HealthApiV1HealthGetData>) =>
  createQueryKey("healthApiV1HealthGet", options);

/**
 * Health
 *
 * Health check endpoint.
 */
export const healthApiV1HealthGetOptions = (options?: Options<HealthApiV1HealthGetData>) =>
  queryOptions<
    HealthApiV1HealthGetResponse,
    DefaultError,
    HealthApiV1HealthGetResponse,
    ReturnType<typeof healthApiV1HealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthApiV1HealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthApiV1HealthGetQueryKey(options),
  });

export const healthCompatHealthGetQueryKey = (options?: Options<HealthCompatHealthGetData>) =>
  createQueryKey("healthCompatHealthGet", options);

/**
 * Health Compat
 *
 * Compatibility endpoint for existing callers.
 */
export const healthCompatHealthGetOptions = (options?: Options<HealthCompatHealthGetData>) =>
  queryOptions<
    HealthCompatHealthGetResponse,
    DefaultError,
    HealthCompatHealthGetResponse,
    ReturnType<typeof healthCompatHealthGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthCompatHealthGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthCompatHealthGetQueryKey(options),
  });
